export const DISHES = [
  // ---------------------------------------------------------------- Nuwara Eliya
  {
    slug: "tea-eclair",
    name: "Ceylon Tea Éclair",
    region: "nuwara-eliya",
    category: "sweet",
    icon: "🍵",
    subtitle: "The First Taste of Tea",
    keyIngredient: "Ceylon tea crème",
    ingredients: [
      "Choux pastry",
      "Ceylon tea-infused cream",
      "Ceylon tea glaze",
    ],
    story:
      "Once, the hills of Nuwara Eliya were quiet, mist-covered highlands. Then came the tea.\n\nBy the late 19th century, tea estates were spreading across the cool mountains, and Nuwara Eliya became known for producing some of Ceylon's finest tea. Inspired by those early tea days, our éclair brings the delicate flavour of the highlands into a French pastry — a meeting of old Ceylon and new patisserie.",
    modernTwist:
      "Choux pastry filled with Ceylon tea-infused cream and topped with a delicate Ceylon tea glaze.",
    image: "/images/dishes/tea-eclair.jpg",
    featured: true,
    qrCodeId: "KC-NE-TEAEC",
  },
  {
    slug: "tea-tiramisu",
    name: "Tea Tiramisu",
    region: "nuwara-eliya",
    category: "sweet",
    icon: "🍵",
    subtitle: "A Story from the Tea Hills",
    keyIngredient: "Ceylon tea soak",
    ingredients: [
      "Ceylon tea-soaked ladyfingers",
      "Mascarpone cream",
      "Cocoa powder",
    ],
    story:
      "Imagine Nuwara Eliya in an earlier time, when the cool mountain air drew travellers towards the hills and the landscape slowly became covered in endless tea gardens.\n\nAs the first tea leaves were harvested, their fragrance became part of life in the highlands. Our Tea Tiramisu brings that memory to the table, replacing the familiar coffee with fragrant Ceylon tea.\n\nA classic dessert retold through the misty hills and timeless tea heritage of Nuwara Eliya.",
    modernTwist:
      "Ceylon tea-soaked ladyfingers layered with mascarpone cream and finished with a dusting of cocoa powder.",
    image: "/images/dishes/tea-tiramisu.jpg",
    featured: false,
    qrCodeId: "KC-NE-TEATI",
  },
  {
    slug: "nuwara-tea-smoked-chicken-tart",
    name: "Nuwara Tea Smoked Chicken Tart",
    region: "nuwara-eliya",
    category: "savoury",
    icon: "🥧",
    subtitle: "Smoke Over the Estates",
    keyIngredient: "Tea-smoked chicken",
    ingredients: [
      "Ceylon tea smoked chicken",
      "Leeks",
      "Potato",
      "Herbs",
      "Buttery tart shell",
    ],
    story:
      "In old Nuwara Eliya, tea was more than something served in a cup — it was becoming the identity of the hills.\n\nAs tea estates grew during the late 19th century, the scent of freshly made Ceylon tea became part of life in the high country. We capture a little of that character by gently smoking our chicken with Ceylon tea before placing it inside a buttery tart. A savoury dish inspired by the beginning of the tea country.",
    modernTwist:
      "Buttery savoury tart filled with Ceylon tea smoked chicken, leeks, potato and herbs.",
    image: "/images/dishes/nuwara-tea-smoked-chicken-tart.jpg",
    featured: true,
    qrCodeId: "KC-NE-NUWARA",
  },
  {
    slug: "nuwara-eliya-potato-rosti",
    name: "Nuwara Eliya Potato Rosti",
    region: "nuwara-eliya",
    category: "savoury",
    icon: "🥔",
    subtitle: "From the First Highland Farms",
    keyIngredient: "Highland potatoes",
    ingredients: [
      "Highland potatoes",
      "Onion",
      "Fresh herbs",
      "Ceylon pepper",
    ],
    story:
      "Before Nuwara Eliya became famous for tea, people were already looking to its cool mountains for farming.\n\nIn the 19th century, agricultural pioneers such as Samuel Baker established farms in the area and experimented with crops and livestock. Inspired by that early farming story, our potato rosti celebrates the humble produce of the highlands — crispy, golden and simple.",
    modernTwist:
      "Grated highland potatoes fried until golden, finished with onion, fresh herbs and Ceylon pepper.",
    image: "/images/dishes/nuwara-eliya-potato-rosti.jpg",
    featured: false,
    qrCodeId: "KC-NE-ROSTI",
  },
  {
    slug: "nuwara-eliya-mushroom-herb-soup",
    name: "Nuwara Eliya Creamy Mushroom & Herb Soup",
    region: "nuwara-eliya",
    category: "savoury",
    icon: "🍄",
    subtitle: "The Quieter Nuwara Eliya",
    keyIngredient: "Highland mushrooms",
    ingredients: [
      "Highland mushrooms",
      "Cream",
      "Thyme",
      "Garlic",
      "Fresh herbs",
    ],
    story:
      "There is an older Nuwara Eliya hidden beneath the famous tea fields — a place of cold mornings, forests and mountain mist.\n\nBefore the hills became covered with plantations, the highlands were valued for their cool climate and natural surroundings. This warm mushroom and herb soup is inspired by that quieter side of Nuwara Eliya — earthy flavours created for a cold mountain morning.",
    modernTwist:
      "Creamy soup of highland mushrooms with garlic, thyme and a scatter of fresh mountain herbs.",
    image: "/images/dishes/nuwara-eliya-mushroom-herb-soup.jpg",
    featured: false,
    qrCodeId: "KC-NE-MUSH",
  },
  {
    slug: "nuwara-tea-strawberry-bonbon",
    name: "Nuwara Tea & Strawberry Bonbon",
    region: "nuwara-eliya",
    category: "sweet",
    icon: "🍓",
    subtitle: "Two Tastes of the Highlands",
    keyIngredient: "Ceylon tea & strawberry",
    ingredients: [
      "Ceylon tea ganache",
      "Highland strawberry",
      "Dark chocolate shell",
    ],
    story:
      "The story of Nuwara Eliya was never only about tea.\n\nIts cool mountain climate also made the region a place for highland farming, where fresh produce became part of its identity. We bring two flavours associated with the modern highlands — Ceylon tea and strawberries — together inside one delicate bonbon. A tiny sweet story from the hills.",
    modernTwist:
      "A dark chocolate shell holding Ceylon tea ganache and a whole highland strawberry.",
    image: "/images/dishes/nuwara-tea-strawberry-bonbon.jpg",
    featured: false,
    qrCodeId: "KC-NE-STRAW",
  },
  {
    slug: "strawberry-ceylon-tea-fizz",
    name: "Strawberry Ceylon Tea Fizz",
    region: "nuwara-eliya",
    category: "drink",
    icon: "🍓",
    subtitle: "A Sip from the Misty Hills",
    keyIngredient: "Ceylon tea & strawberry",
    ingredients: [
      "Ceylon tea",
      "Highland strawberry",
      "Sparkling water",
      "Mint",
    ],
    story:
      "Imagine arriving in Nuwara Eliya long ago, where the cool mountain air, misty mornings and endless green hills offered a world far removed from the warmth of the lowlands.\n\nAs tea became part of the highland landscape, the hills gained a character of their own. Inspired by those cool mornings, our drink combines fragrant Ceylon tea with sweet strawberry and a gentle sparkle.\n\nA refreshing little story from the tea-covered hills of Nuwara Eliya.",
    modernTwist:
      "Brewed Ceylon tea lengthened with strawberry and a gentle sparkle, lifted with mint.",
    image: "/images/dishes/strawberry-ceylon-tea-fizz.jpg",
    featured: false,
    qrCodeId: "KC-NE-FIZZ",
  },
  {
    slug: "nuwara-milk-tea",
    name: "Nuwara Milk Tea",
    region: "nuwara-eliya",
    category: "drink",
    icon: "🥛",
    subtitle: "An Evening in the Tea Hills",
    keyIngredient: "Strong Ceylon tea",
    ingredients: [
      "Strong Ceylon tea",
      "Warm milk",
      "Sugar",
      "Cardamom",
    ],
    story:
      "Imagine an old evening in Nuwara Eliya, when mist slowly drifted across the tea-covered hills and the cool mountain air settled over the town.\n\nAfter a long day among the plantations, a warm cup of freshly brewed Ceylon tea offered a simple moment of comfort. Our Nuwara Milk Tea brings that feeling to life with strong tea softened with warm, creamy milk.\n\nA warm taste of Nuwara Eliya — where misty hills, quiet evenings and Ceylon tea became part of everyday life.",
    modernTwist:
      "Strong highland tea pulled long and softened with warm milk, lifted with a touch of cardamom.",
    image: "/images/dishes/nuwara-milk-tea.jpg",
    featured: true,
    qrCodeId: "KC-NE-MILK",
  },

  // ------------------------------------------------------------------ Kurunegala
  {
    slug: "athugala-chicken-pie",
    name: "Athugala Chicken Pie",
    region: "kurunegala",
    category: "savoury",
    icon: "🥧",
    subtitle: "A Meal Beneath the Elephant Rock",
    keyIngredient: "Spiced Sri Lankan chicken",
    ingredients: [
      "Chicken",
      "Sri Lankan spices",
      "Coconut cream",
      "Roasted cashews",
      "Pastry crust",
    ],
    story:
      "Long ago, Kurunegala stood as a royal capital, with the great Athugala rock watching over the city. Around it were villages, fields and kitchens where everyday meals were created from what the land provided.\n\nOur Athugala Chicken Pie brings that feeling into a modern pastry. Fragrant Sri Lankan spices, tender chicken, creamy coconut and roasted cashews are wrapped inside a golden crust.\n\nThe pie itself is our modern creation, but its flavours are inspired by the ingredients and cooking traditions that have long been part of Sri Lankan food.",
    modernTwist:
      "Fragrant spiced chicken and coconut wrapped in a golden pastry crust.",
    pullQuote: "Beneath Athugala, familiar flavours become a new story.",
    image: "/images/dishes/athugala-chicken-pie.jpg",
    featured: true,
    qrCodeId: "KC-KG-PIE",
  },
  {
    slug: "athugala-sharing-board",
    name: "Athugala Sharing Board",
    region: "kurunegala",
    category: "savoury",
    icon: "🥥",
    subtitle: "The Table That Brought Everyone Together",
    keyIngredient: "Coconut roti & spices",
    ingredients: [
      "Coconut roti",
      "Fiery sambols",
      "Jackfruit",
      "Spiced chicken",
      "Savoury pastries",
      "Roasted cashews",
    ],
    story:
      "Imagine an old evening in Kurunegala. The day's work is finished, food is placed in the centre of the table, and everyone gathers around to share.\n\nOur Athugala Sharing Board celebrates that simple tradition. Warm coconut roti, fiery sambols, jackfruit, spiced chicken, savoury pastries and roasted cashews come together on one board. Each element is inspired by familiar Sri Lankan ingredients and flavours, brought together in a modern way.",
    modernTwist:
      "A generous board of coconut roti, sambols, jackfruit, spiced chicken and roasted cashews.",
    pullQuote: "Because in Sri Lanka, a good meal was never meant to be enjoyed alone.",
    image: "/images/dishes/athugala-sharing-board.jpg",
    featured: false,
    qrCodeId: "KC-KG-BOARD",
  },
  {
    slug: "coconut-tres-leches",
    name: "Coconut Tres Leches",
    region: "kurunegala",
    category: "sweet",
    icon: "🥥",
    subtitle: "From the Coconut Groves",
    keyIngredient: "Coconut",
    ingredients: [
      "Coconut sponge",
      "Three-milk soak",
      "Coconut cream",
      "Toasted coconut",
    ],
    story:
      "Kurunegala is surrounded by coconut plantations, making the coconut an especially fitting ingredient for its story.\n\nFor generations, coconut has been part of the Sri Lankan kitchen — its milk enriching curries, its flesh becoming sambol and its many parts finding a place in everyday life.\n\nOur Coconut Tres Leches takes this familiar ingredient somewhere unexpected. A soft coconut sponge is soaked in a rich three-milk mixture, covered with coconut cream and toasted coconut, then served inside a coconut shell.",
    modernTwist:
      "Coconut sponge soaked in three-milk syrup, served in a coconut shell with cream and toasted coconut.",
    pullQuote:
      "From the coconut groves of Kurunegala, an old island ingredient finds a new form.",
    image: "/images/dishes/coconut-tres-leches.jpg",
    featured: false,
    qrCodeId: "KC-KG-TRES",
  },
  {
    slug: "coconut-prawn-choux",
    name: "Coconut & Prawn Choux",
    region: "kurunegala",
    category: "savoury",
    icon: "🥥",
    subtitle: "From the Coconut Grove to the Table",
    keyIngredient: "Spiced prawns",
    ingredients: [
      "Spiced prawns",
      "Coconut mousse",
      "Lime",
      "Choux pastry",
    ],
    story:
      "Kurunegala has long been surrounded by coconut plantations, making coconut an important part of the landscape and local food culture.\n\nOur Coconut & Prawn Choux brings together the flavours of land and water — spiced prawns, creamy coconut mousse and a touch of lime, enclosed in a delicate savoury choux pastry.\n\nThe choux is our modern creation, inspired by the familiar Sri Lankan combination of coconut, seafood and spice.",
    modernTwist:
      "Delicate choux pastry filled with spiced prawns and coconut mousse, finished with lime.",
    pullQuote:
      "From the coconut groves of Kurunegala to the flavours of the water, one bite brings two sides of Sri Lanka together.",
    image: "/images/dishes/coconut-prawn-choux.jpg",
    featured: false,
    qrCodeId: "KC-KG-CHOUX",
  },
  {
    slug: "kithul-coconut-bonbons",
    name: "Kithul Coconut Bonbon",
    region: "kurunegala",
    category: "sweet",
    icon: "🥜",
    subtitle: "Island Sweetness",
    keyIngredient: "Kithul treacle",
    ingredients: [
      "Kithul treacle",
      "Coconut",
      "Dark chocolate shell",
    ],
    story:
      "Coconut and kithul treacle bring together two familiar tastes of Sri Lankan sweetness. Hidden inside a delicate chocolate shell, they create a little taste of the island in every bite.",
    modernTwist:
      "A soft kithul and coconut centre wrapped in a thin dark chocolate shell.",
    pullQuote: "Old flavours, wrapped in a modern Kathā.",
    image: "/images/dishes/kithul-coconut-bonbons.jpg",
    featured: false,
    qrCodeId: "KC-KG-KITH",
  },
  {
    slug: "spiced-pineapple-cooler",
    name: "Spiced Pineapple Cooler",
    region: "kurunegala",
    category: "drink",
    icon: "🍍",
    subtitle: "A Kurunegala Afternoon",
    keyIngredient: "Sweet pineapple",
    ingredients: [
      "Sweet pineapple",
      "Ceylon cinnamon",
      "Ginger",
      "Coconut water",
    ],
    story:
      "Imagine a warm afternoon beneath the Sri Lankan sun. Sweet pineapple meets fragrant cinnamon and warming ginger in a refreshing drink inspired by the island's tropical flavours.",
    modernTwist:
      "Sweet pineapple lengthened with Ceylon cinnamon and warming ginger.",
    pullQuote: "A little sunshine, a little spice, and a cool escape.",
    image: "/images/dishes/spiced-pineapple-cooler.jpg",
    featured: false,
    qrCodeId: "KC-KG-PINE",
  },
  {
    slug: "cashew-cream-coffee",
    name: "Cashew Cream Coffee",
    region: "kurunegala",
    category: "drink",
    icon: "☕",
    subtitle: "A Quiet Morning in Kurunegala",
    keyIngredient: "Roasted cashew",
    ingredients: [
      "Espresso",
      "Roasted cashew cream",
      "Sugar",
    ],
    story:
      "As the morning begins beneath the warm Kurunegala sun, roasted cashew and rich coffee come together in this smooth creation.",
    modernTwist:
      "A smooth blend of espresso and roasted cashew cream.",
    pullQuote: "A familiar Sri Lankan flavour, reimagined for the modern café.",
    image: "/images/dishes/cashew-cream-coffee.jpg",
    featured: false,
    qrCodeId: "KC-KG-CASHEW",
  },

  // ----------------------------------------------------------------------- Galle
  {
    slug: "creamy-coastal-pasta",
    name: "Creamy Coastal Pasta",
    region: "galle",
    category: "savoury",
    icon: "🍝",
    subtitle: "The Merchant's Supper",
    keyIngredient: "Prawns & cuttlefish",
    ingredients: [
      "Prawns",
      "Cuttlefish",
      "Roasted vegetables",
      "Garlic",
      "Fresh herbs",
      "Cream",
    ],
    story:
      "Long ago, when sailing ships entered Galle Harbour, the town came alive with merchants, sailors and the scents of goods brought from distant shores. Near the harbour, the day's catch would make its way into local kitchens.\n\nInspired by those old evenings, our creamy coastal pasta brings prawns and cuttlefish together with roasted vegetables, garlic and herbs.",
    modernTwist:
      "Prawns and cuttlefish folded through roasted vegetables and herbs in a light cream sauce.",
    pullQuote: "A little taste of the harbour, from an age when every ship carried a new story.",
    image: "/images/dishes/creamy-coastal-pasta.jpg",
    featured: false,
    qrCodeId: "KC-GL-PASTA",
  },
  {
    slug: "passionfruit-dark-chocolate-bonbon",
    name: "Passionfruit & Dark Chocolate Bonbon",
    region: "galle",
    category: "sweet",
    icon: "🍫",
    subtitle: "The Sweet Trade of Galle",
    keyIngredient: "Passionfruit & dark chocolate",
    ingredients: [
      "Dark chocolate",
      "Passionfruit",
    ],
    story:
      "In the old days, Galle's stone streets welcomed travellers from faraway lands, while the harbour brought unfamiliar treasures to the island. Behind the fort walls, different cultures and flavours quietly became part of Galle's story.\n\nOur dark chocolate bonbon reflects that meeting — rich chocolate hiding a bright passionfruit centre.",
    modernTwist:
      "Rich dark chocolate hiding a bright, tangy passionfruit centre.",
    pullQuote: "A small sweet inspired by a town where distant worlds once met.",
    image: "/images/dishes/passionfruit-dark-chocolate-bonbon.jpg",
    featured: false,
    qrCodeId: "KC-GL-PASS",
  },
  {
    slug: "pol-roti-seafood-taco",
    name: "Pol Roti Seafood Taco",
    region: "galle",
    category: "savoury",
    icon: "🥥",
    subtitle: "The Fisherman's Morning",
    keyIngredient: "Fresh seafood",
    ingredients: [
      "Pol roti",
      "Fresh seafood",
      "Coconut sambol",
      "Lime",
    ],
    story:
      "Before the streets of Galle grew busy, fishermen would return from the sea with the morning's catch. In nearby homes, coconut was a familiar part of the kitchen, grated, mixed and cooked into simple foods.\n\nWe imagined that old coastal morning again — crisp pol roti, freshly prepared seafood, coconut sambol and a touch of lime.",
    modernTwist:
      "Crisp pol roti filled with fresh seafood, coconut sambol and lime.",
    pullQuote:
      "An old island flavour, carried from the fishermen's shore to a new generation.",
    image: "/images/dishes/pol-roti-seafood-taco.jpg",
    featured: true,
    qrCodeId: "KC-GL-POL",
  },
  {
    slug: "vanilla-gelato-cinnamon-cookies",
    name: "Vanilla Gelato with Cinnamon Chocolate Chip Cookies",
    region: "galle",
    category: "sweet",
    icon: "🍨",
    subtitle: "The Cinnamon Road",
    keyIngredient: "Ceylon cinnamon",
    ingredients: [
      "Vanilla gelato",
      "Cinnamon chocolate chip cookies",
    ],
    story:
      "There was a time when the scent of cinnamon travelled through Galle alongside merchants and ships. Galle's harbour was an important trading centre, with spices among the goods associated with its commercial history.\n\nOur warm cinnamon cookies and cool vanilla gelato bring that memory to the table — simple, comforting and touched by the island's spice-filled past.",
    modernTwist:
      "Warm cinnamon chocolate chip cookies served with cool vanilla gelato.",
    pullQuote: "A sweet memory of cinnamon, carried on the old trade winds.",
    image: "/images/dishes/vanilla-gelato-cinnamon-cookies.jpg",
    featured: false,
    qrCodeId: "KC-GL-GELATO",
  },
  {
    slug: "king-coconut-lime-cooler",
    name: "King Coconut & Lime Cooler",
    region: "galle",
    category: "drink",
    icon: "🥥",
    subtitle: "Under the Fort Walls",
    keyIngredient: "King coconut",
    ingredients: [
      "King coconut",
      "Fresh lime",
      "Mint",
      "Sparkling water",
    ],
    story:
      "Imagine an afternoon long ago, with the sun high above the old fort walls and the sea breeze moving through the narrow streets. After a long walk along the ramparts, there was nothing more welcome than the freshness of a king coconut.\n\nWe add bright lime and fresh mint to recreate that feeling in a glass.",
    modernTwist:
      "Fresh king coconut lengthened with bright lime, mint and a touch of sparkle.",
    pullQuote: "Cool as the sea breeze that once passed through old Galle.",
    image: "/images/dishes/king-coconut-lime-cooler.jpg",
    featured: false,
    qrCodeId: "KC-GL-KING",
  },
  {
    slug: "passionfruit-sea-breeze",
    name: "Passionfruit Sea Breeze",
    region: "galle",
    category: "drink",
    icon: "🌴",
    subtitle: "When the Ships Came Home",
    keyIngredient: "Passionfruit",
    ingredients: [
      "Passionfruit",
      "Lime",
      "Coconut water",
      "Sparkling soda",
    ],
    story:
      "Long before Galle became the lively town we know today, its harbour welcomed ships crossing the Indian Ocean. Sailors arrived with stories of distant shores while the warm southern sea carried the smell of salt, wind and tropical fruit.\n\nPassionfruit, lime, coconut water and sparkling soda capture that feeling — bright, refreshing and touched by the coast.",
    modernTwist:
      "Passionfruit and lime shaken with coconut water and sparkling soda.",
    pullQuote: "A sip of the southern sea, inspired by the journeys of another age.",
    image: "/images/dishes/passionfruit-sea-breeze.jpg",
    featured: false,
    qrCodeId: "KC-GL-BREEZE",
  },

  // -------------------------------------------------------------------- Colombo
  {
    slug: "coconut-lime-tart",
    name: "Coconut & Lime Tart",
    region: "colombo",
    category: "sweet",
    icon: "🥥",
    subtitle: "A Sweet Afternoon in Old Colombo",
    keyIngredient: "Coconut & lime",
    ingredients: [
      "Coconut cream",
      "Fresh lime",
      "Golden pastry shell",
    ],
    story:
      "Long ago, Colombo's streets were filled with traders, shopkeepers and travellers moving between the harbour and the busy markets. Among the many things sold and carried through the city, the humble coconut remained a familiar part of everyday island life.\n\nInspired by those tropical flavours, our tart brings creamy coconut and bright lime together in a delicate golden shell.",
    modernTwist:
      "Creamy coconut and bright lime set in a delicate golden pastry shell.",
    pullQuote: "A little taste of Colombo, where old streets met the flavours of the island.",
    image: "/images/dishes/coconut-lime-tart.jpg",
    featured: false,
    qrCodeId: "KC-CM-TART",
  },
  {
    slug: "devilled-chicken-bao",
    name: "Devilled Chicken Bao",
    region: "colombo",
    category: "savoury",
    icon: "🍗",
    subtitle: "From the Streets of Old Colombo",
    keyIngredient: "Fiery devilled chicken",
    ingredients: [
      "Devilled chicken",
      "Steamed bao bun",
      "Fresh vegetables",
      "Creamy sambal",
    ],
    story:
      "In old Colombo, the streets around the markets and harbour were never quiet for long. The sounds of merchants, carts and passing travellers mixed with the aromas of spices and freshly cooked food.\n\nInspired by that lively spirit, our devilled chicken brings Sri Lanka's fiery flavours into a soft steamed bao, finished with fresh vegetables and creamy sambal.",
    modernTwist:
      "Sri Lanka's fiery devilled chicken tucked into a soft steamed bao with creamy sambal.",
    pullQuote: "The spirit of old Colombo, wrapped in a new story.",
    image: "/images/dishes/devilled-chicken-bao.jpg",
    featured: true,
    qrCodeId: "KC-CM-BAO",
  },
  {
    slug: "egg-hopper-benedict",
    name: "Egg Hopper Benedict",
    region: "colombo",
    category: "savoury",
    icon: "🍳",
    subtitle: "A Morning in the Old City",
    keyIngredient: "Crisp hopper & soft egg",
    ingredients: [
      "Crisp hopper",
      "Soft egg",
      "Seeni sambol",
      "Curry hollandaise",
    ],
    story:
      "Imagine Colombo in another time — before the morning streets became crowded, when the first kitchens were already awake and the aroma of freshly made hoppers drifted into the streets.\n\nWe take that familiar Sri Lankan breakfast and give it a Colombo twist: a crisp hopper, soft egg, caramelised seeni sambol and creamy curry hollandaise.",
    modernTwist:
      "A crisp hopper with soft egg, seeni sambol and creamy curry hollandaise.",
    pullQuote: "An old island breakfast, remembered in a new way.",
    image: "/images/dishes/egg-hopper-benedict.jpg",
    featured: false,
    qrCodeId: "KC-CM-BENE",
  },
  {
    slug: "lamprais",
    name: "Lamprais",
    region: "colombo",
    category: "savoury",
    icon: "🍃",
    subtitle: "The Parcel of Colombo",
    keyIngredient: "Fragrant rice & meat curry",
    ingredients: [
      "Fragrant rice",
      "Meat curry",
      "Sambols",
      "Banana leaf",
      "Traditional accompaniments",
    ],
    story:
      "In old Colombo, different cultures met around the dining table. From those encounters came dishes that became part of the city's food heritage.\n\nWrapped carefully in a banana leaf, lamprais brings together fragrant rice, rich meat curry, sambols and traditional accompaniments.",
    modernTwist:
      "Fragrant rice and rich curry wrapped to order in a banana leaf parcel.",
    pullQuote: "Unwrap it slowly — every layer carries a piece of Colombo's past.",
    image: "/images/dishes/lamprais.jpg",
    featured: true,
    qrCodeId: "KC-CM-LAMPRAIS",
  },
  {
    slug: "salted-coconut-caramel-bonbon",
    name: "Salted Coconut Caramel Bonbon",
    region: "colombo",
    category: "sweet",
    icon: "🍫",
    subtitle: "A Little Treasure from the Port",
    keyIngredient: "Coconut caramel",
    ingredients: [
      "Dark chocolate",
      "Coconut caramel",
      "Sea salt",
    ],
    story:
      "There was a time when Colombo's harbour was filled with ships arriving from distant shores. Traders brought new flavours to the city while the island's own coconuts, spices and other treasures travelled outward.\n\nOur bonbon turns that old exchange into something small and sweet — chocolate surrounding coconut caramel, finished with a touch of sea salt.",
    modernTwist:
      "Dark chocolate surrounding coconut caramel, finished with a touch of sea salt.",
    pullQuote: "A little Colombo treasure, inspired by the city's trading past.",
    image: "/images/dishes/salted-coconut-caramel-bonbon.jpg",
    featured: false,
    qrCodeId: "KC-CM-CARAMEL",
  },
  {
    slug: "ceylon-cinnamon-mocha",
    name: "Ceylon Cinnamon Mocha",
    region: "colombo",
    category: "drink",
    icon: "☕",
    subtitle: "The Fragrance of Old Colombo",
    keyIngredient: "Ceylon cinnamon",
    ingredients: [
      "Espresso",
      "Ceylon cinnamon",
      "Chocolate",
      "Warm milk",
    ],
    story:
      "Picture the old city when Colombo's trading streets were filled with the fragrance of spices. Among them was Ceylon cinnamon — delicate, warm and unmistakably connected to the island.\n\nToday, that familiar fragrance meets espresso and chocolate in a rich mocha.",
    modernTwist: "Espresso and chocolate lifted with the warmth of Ceylon cinnamon.",
    pullQuote: "A warm cup carrying the scent of an older Colombo.",
    image: "/images/dishes/ceylon-cinnamon-mocha.jpg",
    featured: false,
    qrCodeId: "KC-CM-MOCHA",
  },
  {
    slug: "salted-coconut-cream-coffee",
    name: "Salted Coconut Cream Coffee",
    region: "colombo",
    category: "drink",
    icon: "🥥",
    subtitle: "An Afternoon by the Old Harbour",
    keyIngredient: "Coconut cream cold brew",
    ingredients: [
      "Cold brew coffee",
      "Coconut cream",
      "Condensed milk",
      "Sea salt",
    ],
    story:
      "As the afternoon sun settled over old Colombo, the harbour and its surrounding streets slowly cooled after another busy day. Traders disappeared into cafés, shops closed their shutters, and the city prepared for evening.\n\nInspired by that slower moment, our cold brew is softened with coconut cream, condensed milk and a touch of sea salt.",
    modernTwist:
      "Cold brew softened with coconut cream, condensed milk and a touch of sea salt.",
    pullQuote: "A quiet pause from the old city, reimagined for today.",
    image: "/images/dishes/salted-coconut-cream-coffee.jpg",
    featured: false,
    qrCodeId: "KC-CM-COCOFF",
  },
];

export const DISH_BY_SLUG = Object.fromEntries(DISHES.map((d) => [d.slug, d]));

export const CATEGORIES = [
  { id: "sweet", label: "Sweet" },
  { id: "savoury", label: "Savoury" },
  { id: "drink", label: "Drinks" },
];